typography_spectrum: 0.83568
color:
  brandColors:
    - '#140b06'
    - '#877a79'
    - '#ffffff'
    - '#3d3330'
    - '#965a36'
  brandStrength: 0.3125
  lightness: 0.8715461124666035
  saturation: 0.8314735780004412
  rhythmicContrast: 0.5839146384969354
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.46955
analytics:
  google: null
  facebook: null
  twitter: null
name: americanartistinrome
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: American Artist in Rome
description: 'Paintings, Drawings and Words by Timothy Joseph Allen'
purpose: []
