name: americanartistinrome
favicon: null
layout_spectrum: 0.46955
typography_spectrum: 0.83568
title: American Artist in Rome
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140b06'
    - '#877a79'
    - '#ffffff'
    - '#3d3330'
    - '#965a36'
  brandStrength: 0.3125
  lightness: 0.8715461124666035
  saturation: 0.8314735780004412
  rhythmicContrast: 0.5839146384969354
purpose: []
